application: chat-channelapi
version: 1
runtime: python
api_version: 1

inbound_services:
- channel_presence

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on

handlers:
- url: /static
  static_dir: static
- url: /_ah/channel/.*
  script: connection_handler.py
- url: .*
  script: main.py